openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://kula-web.localhost/api
    description: Local development server

paths:
  /kebab-places:
    get:
      summary: Pobierz listę wszystkich miejsc z kebabami
      description:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Numer strony wyników
          required: false
          example: 1
        - in: query
          name: sby
          schema:
            type: string
            enum: [name, google_maps_rating, id]
          description: Sortuj według pola
          required: false
          example: name
        - in: query
          name: sdirection
          schema:
            type: string
            enum: [asc, desc]
          description: Kierunek sortowania
          required: false
          example: asc
        - in: query
          name: fstatus
          schema:
            type: string
            enum: [otwarte, zamknięte, planowane]
          description: Filtruj według statusu
          required: false
          example: otwarte
        - in: query
          name: fsauces
          schema:
            type: string
          description: Filtruj według id sosów
          required: false
          example: "[1,2]"
        - in: query
          name: ffillings
          schema:
            type: string
          description: Filtruj według id składników
          required: false
          example: "[1,2]"
        - in: query
          name: fordering
          schema:
            type: string
            enum: ["przez telefon", "własna strona", "własna aplikacja", "pyszne.pl", "glovo"]
          description: Filtruj według opcji zamówienia
          required: false
          example: "przez telefon"
        - in: query
          name: flocation
          schema:
            type: string
            enum: ["buda", "lokal"]
          description: Filtruj według lokalizacji
          required: false
          example: "buda"
        - in: query
          name: fcraft
          schema:
            type: string
          description: Filtruj według typu kebaba
          required: false
          example: "true"
        - in: query
          name: fchain
          schema:
            type: string
          description: Filtruj według typu restauracji
          required: false
          example: "true"
      responses:
        "200":
          description: Lista miejsc z kebabami w formacie JSON z paginacją
          content:
            application/json:
              example:
                current_page: 1
                data:
                  - id: 1
                    name: Cyrus Kebab
                    image: kebab-place/cyrus-kebab.jpg
                    address: Rynek 20
                    latitude: "51.20788328467099"
                    longitude: "16.161068016930532"
                    google_maps_url: https://g.co/kgs/c3CxWnh
                    google_maps_rating: null
                    phone: "+48 509 969 117"
                    website: https://www.cyrus.pl/
                    android: null
                    ios: null
                    email: cyrus@cyrus.pl
                    opened_at_year: null
                    closed_at_year: null
                    fillings:
                      - 4
                      - 5
                      - 6
                    sauces:
                      - 3
                      - 5
                      - 6
                      - 7
                    status: otwarte
                    is_craft: false
                    is_chain_restaurant: false
                    location_type: lokal
                    order_options:
                      - przez telefon
                      - własna strona
                    social_media:
                      - name: fb
                        url: https://www.facebook.com/cyruskebab/
                    created_at: 2025-01-19T01:32:08.000000Z
                    updated_at: 2025-01-19T01:32:08.000000Z
                    opening_hours:
                      - day: Poniedziałek
                        from: 10:00
                        to: 22:00
                      - day: Wtorek
                        from: 10:00
                        to: 22:00
                      - day: Środa
                        from: 10:00
                        to: 22:00
                      - day: Czwartek
                        from: 10:00
                        to: 22:00
                      - day: Piątek
                        from: 10:00
                        to: 00:00
                      - day: Sobota
                        from: 10:00
                        to: 00:00
                      - day: Niedziela
                        from: 10:00
                        to: 22:00
                  - id: 2
                    name: Kurczak Pieczony
                    image: kebab-place/kurczak-pieczony-kosmiczna.jpg
                    address: Kosmiczna 2
                    latitude: "51.20960667521959"
                    longitude: "16.187620415522723"
                    google_maps_url: https://maps.app.goo.gl/kuUMqSf1FScGcpDu5
                    google_maps_rating: null
                    phone: "696 385 028"
                    website: null
                    android: null
                    ios: null
                    email: null
                    opened_at_year: null
                    closed_at_year: null
                    fillings:
                      - 1
                      - 2
                    sauces: []
                    status: otwarte
                    is_craft: false
                    is_chain_restaurant: true
                    location_type: buda
                    order_options: []
                    social_media:
                      - name: fb
                        url: https://www.facebook.com/kurczaki.pieczone.3/?locale=pl_PL
                    created_at: 2025-01-19T01:32:08.000000Z
                    updated_at: 2025-01-19T01:32:08.000000Z
                    opening_hours:
                      - day: Poniedziałek
                        from: 10:00
                        to: 19:00
                      - day: Wtorek
                        from: 10:00
                        to: 19:00
                      - day: Środa
                        from: 10:00
                        to: 19:00
                      - day: Czwartek
                        from: 10:00
                        to: 19:00
                      - day: Piątek
                        from: 10:00
                        to: 19:00
                      - day: Sobota
                        from: 10:00
                        to: 18:00
                      - day: Niedziela
                        from: 10:00
                        to: 17:00
                first_page_url: http://localhost:63251/api/kebab-places?page=1
                from: 1
                last_page: 18
                last_page_url: http://localhost:63251/api/kebab-places?page=18
                links:
                  - url: null
                    label: "&laquo; Previous"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=1
                    label: "1"
                    active: true
                  - url: http://localhost:63251/api/kebab-places?page=2
                    label: "2"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=3
                    label: "3"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=4
                    label: "4"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=5
                    label: "5"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=6
                    label: "6"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=7
                    label: "7"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=8
                    label: "8"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=9
                    label: "9"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=10
                    label: "10"
                    active: false
                  - url: null
                    label: "..."
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=17
                    label: "17"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=18
                    label: "18"
                    active: false
                  - url: http://localhost:63251/api/kebab-places?page=2
                    label: "Next &raquo;"
                    active: false
                next_page_url: http://localhost:63251/api/kebab-places?page=2
                path: http://localhost:63251/api/kebab-places
                per_page: 2
                prev_page_url: null
                to: 2
                total: 35
  /kebab-places/{kebabPlace}:
    get:
      summary: Pobierz szczegóły miejsca z kebabami
      description:
      responses:
        "200":
          description: Szczegóły miejsca z kebabami w formacie JSON
          content:
            application/json:
              schema:
                type: object
  /register:
    post:
      summary: Zarejestruj nowego użytkownika
      description:
      responses:
        "201":
          description: Użytkownik zarejestrowany
          content:
            application/json:
              schema:
                type: object
  /login:
    post:
      summary: Zaloguj użytkownika
      description:
      responses:
        "200":
          description: Użytkownik zalogowany
          content:
            application/json:
              schema:
                type: object
  /user:
    get:
      summary: Pobierz dane zalogowanego użytkownika
      description:
      responses:
        "200":
          description: Dane użytkownika
          content:
            application/json:
              schema:
                type: object
    patch:
      summary: Zaktualizuj dane zalogowanego użytkownika
      description:
      responses:
        "200":
          description: Dane użytkownika zaktualizowane
          content:
            application/json:
              schema:
                type: object
  /logout:
    post:
      summary: Wyloguj użytkownika
      description:
      responses:
        "200":
          description: Użytkownik wylogowany
          content:
            application/json:
              schema:
                type: object
  /sauces:
    get:
      summary: Pobierz listę wszystkich sosów
      description:
      responses:
        "200":
          description: Lista sosów w formacie JSON
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /fillings:
    get:
      summary: Pobierz listę wszystkich składników
      description:
      responses:
        "200":
          description: Lista składników w formacie JSON
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /kebab-places/{kebabPlace}/fav:
    put:
      summary: Dodaj miejsce do ulubionych
      description:
      responses:
        "200":
          description: Dodano do ulubionych
          content:
            application/json:
              schema:
                type: object
  /kebab-places/{kebabPlace}/unfav:
    delete:
      summary: Usuń miejsce z ulubionych
      description:
      responses:
        "200":
          description: Usunięto z ulubionych
          content:
            application/json:
              schema:
                type: object
  /kebab-places/{kebabPlace}/comment:
    post:
      summary: Dodaj komentarz do miejsca
      description:
      responses:
        "200":
          description: Dodano komentarz
          content:
            application/json:
              schema:
                type: object
  /comment/{comment}:
    patch:
      summary: Edytuj komentarz
      description:
      responses:
        "200":
          description: Edytowano komentarz
          content:
            application/json:
              schema:
                type: object
    delete:
      summary: Usuń komentarz
      description:
      responses:
        "200":
          description: Komentarz usunięty
          content:
            application/json:
              schema:
                type: object
  /kebab-places/{kebabPlace}/suggest:
    post:
      summary: Zarejestruj nowe sugestie
      description:
      responses:
        "201":
          description: Sugestie zarejestrowane
          content:
            application/json:
              schema:
                type: object
  /mysuggestions:
    get:
      summary: Pobierz sugestie użytkownika
      description:
      responses:
        "200":
          description: Lista sugestii
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
